### ISSUE TITLE
Installation folder 'extensions' no longer needed in latest CC version

### ISSUE THREAD

**Issue by jleaders** [csnate/cctray-jenkins-transport#16]
As far as I can tell, CCTray did not find it when I put the *.dll in 'extensions' (As the Readme.md recommended)
But when I took it out of the 'extensions' folder and just placed it in the root CCTray folder (Program Files/CCTray) it worked.

One more note, you may want to include a download link to the pre-built *.dll

**Comment by csnate** [comment]
What version of CCTray are you running?

As for the pre-build assemblies, check out the Releases tab under Code.

**Comment by csnate** [comment]
README updated and I've included a link to the releases section as well.

**Comment by jleaders** [comment]
I apologize, it's a little more nuanced than that. I was wrong. So the 'extensions' folder must be present, but then the *.dll can be in it or in the root dir. We might as well tell people to just put it in the 'extensions' dir. Sorry for the confusion.

**Comment by csnate** [comment]
No worries. I'll update the readme.

**Comment by jleaders** [comment]
I found out after I posted this that Catlight.io supports jenkins setups like this out of the box now without an extension

**Comment by csnate** [comment]
Cool, have you had a chance to try it out yet?  Does it support multiple Jenkins instances?

**Comment by jleaders** [comment]
Not sure about multiple jenkins instances, but I use it for my one Jenkins and Catlight works great.
