### ISSUE TITLE
Update Readme.md with password expiration workaround

### ISSUE THREAD

**Issue by piranout** [csnate/cctray-jenkins-transport#17]
The Readme mentions that: 

> If you are using a username and password and you change your password, you cannot update your password (clicking Configure for the server doesn't work again). You have to remove all projects and add the server again.

Users can avoid this. Simply use a Jenkins-issued API Token instead of your password.

1. Log into Jenkins
2. Click your username (in the upper right corner)
3. Click `Configure` (in the left navbar)
4. Click `Show API Token`
5. Use this token in place of your password when setting up the Jenkins Transport settings

**Comment by csnate** [comment]
What version of Jenkins are you using?

**Comment by piranout** [comment]
Works in 2.18 and 2.20, at least.

**Comment by csnate** [comment]
Cool!  Readme updated.
